---
version: '3'
services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    ports:
      - 13306:3306
    environment:
      MYSQL_DATABASE: dbquota
      MYSQL_ROOT_PASSWORD: test
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - ${PWD}/mariadb/db/:/var/lib/mysql
