---
version: '3'
services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    ports:
      - 13306:3306
    environment:
      MYSQL_DATABASE: dbquota
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - ${PWD}/mariadb/conf.d/:/etc/mysql/conf.d
      - ${PWD}/mariadb/db/:/var/lib/mysql
